#!/bin/sh
REFRESH="MyWorkspace:/.refresh"
BREAK="MyWorkspace:/.break"
while true 
do
	echo "waiting for refresh event..."
	if test -f "$REFRESH"; then
    		echo "$REFRESH exist"
		System:Rexxc/rx DOPUS5:Arexx/refresh.dopus5
		rm $REFRESH
	fi
	if test -f "$BREAK"; then
			echo "Break file found. Exiting..."
		break
	fi
	sleep 1
done

rm $BREAK