#!/bin/sh

# This daemon refresh the screen of Icaros by calling the Arexx dopus script
# It has to run on Icaros
# It refresh the screen when it find the file: $REFRESH
# It exit when it find the file: $BREAK

REFRESH="/MyWorkspace/.refresh"
BREAK="/MyWorkspace/.break"
while true 
do
	echo "waiting for refresh event..."
	if test -f "$REFRESH"; then
    		echo "$REFRESH exist"
		System:Rexxc/rx DOPUS5:Arexx/refresh.dopus5
		rm $REFRESH
	fi
	if test -f "$BREAK"; then
		echo "Break file found. Exiting..."
		break
	fi
	sleep 1
done
